In [3]:
import numpy as np

In [4]:
import pandas as pd
df = pd.read_csv("air_quality_historical.csv")

In [5]:
df

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,european_aqi
0,2022-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-08-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-08-04,27.152632,18.984211,328.157895,13.226316,5.373684,75.526316,0.491053,0.421053,2.094737,NaN,NaN
4,2022-08-05,15.529167,10.879167,237.875000,13.645833,6.395833,52.833333,0.221667,0.000000,1.066667,55.315789,29.157895
...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2026-02-14,50.154167,48.300000,673.416667,10.266667,14.766667,127.916667,0.460833,2.875000,1.810417,125.416667,75.708333
1294,2026-02-15,62.729167,60.625000,845.750000,15.004167,15.500000,126.958333,0.678333,3.625000,1.735417,144.166667,82.500000
1295,2026-02-16,70.454167,68.583333,687.208333,13.158333,15.329167,130.000000,0.698750,3.208333,1.702083,156.500000,94.250000
1296,2026-02-17,51.379167,50.233333,552.916667,7.229167,12.458333,127.333333,0.540833,1.916667,1.879167,150.250000,87.250000
1297,2026-02-18,43.029167,41.875000,540.666667,6.883333,11.441667,123.666667,0.430417,1.625000,1.975000,124.083333,75.916667

In [6]:
df.shape

(1298, 12)

In [7]:
df.info

<bound method DataFrame.info of             date       pm10      pm2_5  carbon_monoxide  nitrogen_dioxide  \
0     2022-08-01        NaN        NaN              NaN               NaN
1     2022-08-02        NaN        NaN              NaN               NaN
2     2022-08-03        NaN        NaN              NaN               NaN
3     2022-08-04  27.152632  18.984211       328.157895         13.226316
4     2022-08-05  15.529167  10.879167       237.875000         13.645833
...          ...        ...        ...              ...               ...
1293  2026-02-14  50.154167  48.300000       673.416667         10.266667
1294  2026-02-15  62.729167  60.625000       845.750000         15.004167
1295  2026-02-16  70.454167  68.583333       687.208333         13.158333
1296  2026-02-17  51.379167  50.233333       552.916667          7.229167
1297  2026-02-18  43.029167  41.875000       540.666667          6.883333

      sulphur_dioxide       ozone  aerosol_optical_depth      dust  uv_index  \
0                 NaN         NaN                    NaN       NaN       NaN
1                 NaN         NaN                    NaN       NaN       NaN
2                 NaN         NaN                    NaN       NaN       NaN
3            5.373684   75.526316               0.491053  0.421053  2.094737
4            6.395833   52.833333               0.221667  0.000000  1.066667
...               ...         ...                    ...       ...       ...
1293        14.766667  127.916667               0.460833  2.875000  1.810417
1294        15.500000  126.958333               0.678333  3.625000  1.735417
1295        15.329167  130.000000               0.698750  3.208333  1.702083
1296        12.458333  127.333333               0.540833  1.916667  1.879167
1297        11.441667  123.666667               0.430417  1.625000  1.975000

          us_aqi  european_aqi
0            NaN           NaN
1            NaN           NaN
2            NaN           NaN
3            NaN           NaN
4      55.315789     29.157895
...          ...           ...
1293  125.416667     75.708333
1294  144.166667     82.500000
1295  156.500000     94.250000
1296  150.250000     87.250000
1297  124.083333     75.916667

[1298 rows x 12 columns]>

In [8]:
print("Dataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

Dataset Shape:
(1298, 12)

Column Names:
['date', 'pm10', 'pm2_5', 'carbon_monoxide', 'nitrogen_dioxide', 'sulphur_dioxide', 'ozone', 'aerosol_optical_depth', 'dust', 'uv_index', 'us_aqi', 'european_aqi']

Data Types:
date                         str
pm10                     float64
pm2_5                    float64
carbon_monoxide          float64
nitrogen_dioxide         float64
sulphur_dioxide          float64
ozone                    float64
aerosol_optical_depth    float64
dust                     float64
uv_index                 float64
us_aqi                   float64
european_aqi             float64
dtype: object

Missing Values:
date                     0
pm10                     3
pm2_5                    3
carbon_monoxide          3
nitrogen_dioxide         3
sulphur_dioxide          3
ozone                    3
aerosol_optical_depth    3
dust                     3
uv_index                 3
us_aqi                   4
european_aqi             4
dtype: int64

Duplicate Rows:
0

In [9]:
df['date'] = pd.to_datetime(df['date'])

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [11]:
print(df.isnull().sum())

date                     0
pm10                     3
pm2_5                    3
carbon_monoxide          3
nitrogen_dioxide         3
sulphur_dioxide          3
ozone                    3
aerosol_optical_depth    3
dust                     3
uv_index                 3
us_aqi                   4
european_aqi             4
dtype: int64

In [12]:
df[df.isnull().any(axis=1)]

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,us_aqi,european_aqi
0,2022-08-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-08-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-08-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-08-04,27.152632,18.984211,328.157895,13.226316,5.373684,75.526316,0.491053,0.421053,2.094737,NaN,NaN

In [13]:
pollutant_columns = [
    'pm10',
    'pm2_5',
    'carbon_monoxide',
    'nitrogen_dioxide',
    'sulphur_dioxide',
    'ozone'
]

print(df[pollutant_columns].isnull().sum())

pm10                3
pm2_5               3
carbon_monoxide     3
nitrogen_dioxide    3
sulphur_dioxide     3
ozone               3
dtype: int64

In [14]:
df.head

<bound method NDFrame.head of            date       pm10      pm2_5  carbon_monoxide  nitrogen_dioxide  \
0    2022-08-01        NaN        NaN              NaN               NaN
1    2022-08-02        NaN        NaN              NaN               NaN
2    2022-08-03        NaN        NaN              NaN               NaN
3    2022-08-04  27.152632  18.984211       328.157895         13.226316
4    2022-08-05  15.529167  10.879167       237.875000         13.645833
...         ...        ...        ...              ...               ...
1293 2026-02-14  50.154167  48.300000       673.416667         10.266667
1294 2026-02-15  62.729167  60.625000       845.750000         15.004167
1295 2026-02-16  70.454167  68.583333       687.208333         13.158333
1296 2026-02-17  51.379167  50.233333       552.916667          7.229167
1297 2026-02-18  43.029167  41.875000       540.666667          6.883333

      sulphur_dioxide       ozone  aerosol_optical_depth      dust  uv_index  \
0                 NaN         NaN                    NaN       NaN       NaN
1                 NaN         NaN                    NaN       NaN       NaN
2                 NaN         NaN                    NaN       NaN       NaN
3            5.373684   75.526316               0.491053  0.421053  2.094737
4            6.395833   52.833333               0.221667  0.000000  1.066667
...               ...         ...                    ...       ...       ...
1293        14.766667  127.916667               0.460833  2.875000  1.810417
1294        15.500000  126.958333               0.678333  3.625000  1.735417
1295        15.329167  130.000000               0.698750  3.208333  1.702083
1296        12.458333  127.333333               0.540833  1.916667  1.879167
1297        11.441667  123.666667               0.430417  1.625000  1.975000

          us_aqi  european_aqi
0            NaN           NaN
1            NaN           NaN
2            NaN           NaN
3            NaN           NaN
4      55.315789     29.157895
...          ...           ...
1293  125.416667     75.708333
1294  144.166667     82.500000
1295  156.500000     94.250000
1296  150.250000     87.250000
1297  124.083333     75.916667

[1298 rows x 12 columns]>

In [15]:
df[pollutant_columns] = df[pollutant_columns].interpolate()
df[pollutant_columns] = df[pollutant_columns].ffill().bfill()
print(df[pollutant_columns].isnull().sum())

pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dtype: int64

In [16]:
print((df[pollutant_columns] < 0).sum())

pm10                0
pm2_5               0
carbon_monoxide     0
nitrogen_dioxide    0
sulphur_dioxide     0
ozone               0
dtype: int64

In [17]:
print("Shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicates:", df.duplicated().sum())

print("\nData types:")
print(df.dtypes)

Shape: (1298, 12)

Missing values:
date                     0
pm10                     0
pm2_5                    0
carbon_monoxide          0
nitrogen_dioxide         0
sulphur_dioxide          0
ozone                    0
aerosol_optical_depth    3
dust                     3
uv_index                 3
us_aqi                   4
european_aqi             4
dtype: int64

Duplicates: 0

Data types:
date                     datetime64[us]
pm10                            float64
pm2_5                           float64
carbon_monoxide                 float64
nitrogen_dioxide                float64
sulphur_dioxide                 float64
ozone                           float64
aerosol_optical_depth           float64
dust                            float64
uv_index                        float64
us_aqi                          float64
european_aqi                    float64
dtype: object

In [18]:
pollutant_columns = [
    'pm10',
    'pm2_5',
    'carbon_monoxide',
    'nitrogen_dioxide',
    'sulphur_dioxide',
    'ozone'
]

In [19]:
pm25_breakpoints = [
    (0.0, 9.0, 0, 50),
    (9.1, 35.4, 51, 100),
    (35.5, 55.4, 101, 150),
    (55.5, 125.4, 151, 200),
    (125.5, 225.4, 201, 300),
    (225.5, 325.4, 301, 500)
]

In [20]:
def calculate_aqi(C, breakpoints):

    for Clow, Chigh, Ilow, Ihigh in breakpoints:

        if Clow <= C <= Chigh:

            AQI = ((Ihigh - Ilow) / (Chigh - Clow)) * \
                  (C - Clow) + Ilow

            return AQI

    return np.nan

In [21]:
calculate_aqi(40, pm25_breakpoints)

112.08040201005025

In [22]:
df['pm2_5_aqi'] = df['pm2_5'].apply(
    lambda x: calculate_aqi(x, pm25_breakpoints)
)

In [23]:
print(df[['pm2_5', 'pm2_5_aqi']].head())

       pm2_5  pm2_5_aqi
0  18.984211  69.415449
1  18.984211  69.415449
2  18.984211  69.415449
3  18.984211  69.415449
4  10.879167  54.314797

In [24]:
pm10_breakpoints = [
    (0, 54, 0, 50),
    (55, 154, 51, 100),
    (155, 254, 101, 150),
    (255, 354, 151, 200),
    (355, 424, 201, 300),
    (425, 504, 301, 500)
]
df['pm10_aqi'] = df['pm10'].apply(
    lambda x: calculate_aqi(x, pm10_breakpoints)
)

In [25]:
print(df[['pm10', 'pm10_aqi']].head())

        pm10   pm10_aqi
0  27.152632  25.141326
1  27.152632  25.141326
2  27.152632  25.141326
3  27.152632  25.141326
4  15.529167  14.378858

In [26]:
co_breakpoints = [
    (0.0, 4.4, 0, 50),
    (4.5, 9.4, 51, 100),
    (9.5, 12.4, 101, 150),
    (12.5, 15.4, 151, 200),
    (15.5, 30.4, 201, 300),
    (30.5, 50.4, 301, 500)
]
df['co_aqi'] = df['carbon_monoxide'].apply(
    lambda x: calculate_aqi(x, co_breakpoints)
)
print(df[['carbon_monoxide', 'co_aqi']].head())

   carbon_monoxide  co_aqi
0       328.157895     NaN
1       328.157895     NaN
2       328.157895     NaN
3       328.157895     NaN
4       237.875000     NaN

In [27]:
print(df['carbon_monoxide'].describe())

count    1298.000000
mean      429.168341
std       193.642269
min        59.041667
25%       277.656250
50%       412.479167
75%       546.375000
max      1554.833333
Name: carbon_monoxide, dtype: float64

In [28]:
print(df['carbon_monoxide'].head())

0    328.157895
1    328.157895
2    328.157895
3    328.157895
4    237.875000
Name: carbon_monoxide, dtype: float64

In [29]:
print(df[['carbon_monoxide', 'pm2_5', 'pm10']].head())

   carbon_monoxide      pm2_5       pm10
0       328.157895  18.984211  27.152632
1       328.157895  18.984211  27.152632
2       328.157895  18.984211  27.152632
3       328.157895  18.984211  27.152632
4       237.875000  10.879167  15.529167

In [30]:
no2_breakpoints = [
    (0, 53, 0, 50),
    (54, 100, 51, 100),
    (101, 360, 101, 150),
    (361, 649, 151, 200),
    (650, 1249, 201, 300),
    (1250, 2049, 301, 500)
]
df['no2_ppb'] = df['nitrogen_dioxide'] * 24.45 / 46.0055
df['no2_aqi'] = df['no2_ppb'].apply(
    lambda x: calculate_aqi(x, no2_breakpoints)
)
print(df[['nitrogen_dioxide', 'no2_ppb', 'no2_aqi']].head())

   nitrogen_dioxide   no2_ppb   no2_aqi
0         13.226316  7.029234  6.631353
1         13.226316  7.029234  6.631353
2         13.226316  7.029234  6.631353
3         13.226316  7.029234  6.631353
4         13.645833  7.252190  6.841689

In [31]:
so2_breakpoints = [
    (0, 35, 0, 50),
    (36, 75, 51, 100),
    (76, 185, 101, 150),
    (186, 304, 151, 200),
    (305, 604, 201, 300),
    (605, 1004, 301, 500)
]
df['so2_ppb'] = df['sulphur_dioxide'] * 24.45 / 64.066
df['so2_aqi'] = df['so2_ppb'].apply(
    lambda x: calculate_aqi(x, so2_breakpoints)
)
print(df[['sulphur_dioxide', 'so2_ppb', 'so2_aqi']].head())

   sulphur_dioxide   so2_ppb   so2_aqi
0         5.373684  2.050800  2.929715
1         5.373684  2.050800  2.929715
2         5.373684  2.050800  2.929715
3         5.373684  2.050800  2.929715
4         6.395833  2.440891  3.486987

In [32]:
o3_breakpoints = [
    (0, 54, 0, 50),
    (55, 70, 51, 100),
    (71, 85, 101, 150),
    (86, 105, 151, 200),
    (106, 200, 201, 300),
    (201, 604, 301, 500)
]
df['o3_ppb'] = df['ozone'] * 24.45 / 47.9982
df['o3_aqi'] = df['o3_ppb'].apply(
    lambda x: calculate_aqi(x, o3_breakpoints)
)
print(df[['ozone', 'o3_ppb', 'o3_aqi']].head())

       ozone     o3_ppb     o3_aqi
0  75.526316  38.472660  35.622833
1  75.526316  38.472660  35.622833
2  75.526316  38.472660  35.622833
3  75.526316  38.472660  35.622833
4  52.833333  26.912988  24.919434

In [33]:
aqi_columns = [
    'pm2_5_aqi',
    'pm10_aqi',
    'co_aqi',
    'no2_aqi',
    'so2_aqi',
    'o3_aqi'
]
df['calculated_aqi'] = df[aqi_columns].max(axis=1)
print(df[aqi_columns + ['calculated_aqi']].head())

   pm2_5_aqi   pm10_aqi  co_aqi   no2_aqi   so2_aqi     o3_aqi  calculated_aqi
0  69.415449  25.141326     NaN  6.631353  2.929715  35.622833       69.415449
1  69.415449  25.141326     NaN  6.631353  2.929715  35.622833       69.415449
2  69.415449  25.141326     NaN  6.631353  2.929715  35.622833       69.415449
3  69.415449  25.141326     NaN  6.631353  2.929715  35.622833       69.415449
4  54.314797  14.378858     NaN  6.841689  3.486987  24.919434       54.314797

In [34]:
print(co_breakpoints)
print(df['carbon_monoxide'].min())
print(df['carbon_monoxide'].max())

[(0.0, 4.4, 0, 50), (4.5, 9.4, 51, 100), (9.5, 12.4, 101, 150), (12.5, 15.4, 151, 200), (15.5, 30.4, 201, 300), (30.5, 50.4, 301, 500)]
59.04166666666666
1554.8333333333333

In [35]:
df['co_ppm'] = df['carbon_monoxide'] * 24.45 / (28.01 * 1000)
df['co_aqi'] = df['co_ppm'].apply(
    lambda x: calculate_aqi(x, co_breakpoints)
)
print(df[['carbon_monoxide', 'co_ppm', 'co_aqi']].head())

   carbon_monoxide    co_ppm    co_aqi
0       328.157895  0.286450  3.255112
1       328.157895  0.286450  3.255112
2       328.157895  0.286450  3.255112
3       328.157895  0.286450  3.255112
4       237.875000  0.207642  2.359565

In [36]:
df['calculated_aqi'] = df[aqi_columns].max(axis=1)
print(df[aqi_columns + ['calculated_aqi']].head())

   pm2_5_aqi   pm10_aqi    co_aqi   no2_aqi   so2_aqi     o3_aqi  \
0  69.415449  25.141326  3.255112  6.631353  2.929715  35.622833
1  69.415449  25.141326  3.255112  6.631353  2.929715  35.622833
2  69.415449  25.141326  3.255112  6.631353  2.929715  35.622833
3  69.415449  25.141326  3.255112  6.631353  2.929715  35.622833
4  54.314797  14.378858  2.359565  6.841689  3.486987  24.919434

   calculated_aqi
0       69.415449
1       69.415449
2       69.415449
3       69.415449
4       54.314797

In [37]:
def classify_aqi(aqi):
    if aqi <= 50:
        return "Good"
    elif aqi <= 100:
        return "Moderate"
    elif aqi <= 150:
        return "Poor"
    elif aqi <= 200:
        return "Severe"
    else:
        return "Very Severe"

In [38]:
df['aqi_category'] = df['calculated_aqi'].apply(classify_aqi)

In [39]:
print(df[['calculated_aqi', 'aqi_category']].head(10))

   calculated_aqi aqi_category
0       69.415449     Moderate
1       69.415449     Moderate
2       69.415449     Moderate
3       69.415449     Moderate
4       54.314797     Moderate
5       38.935185         Good
6       31.990741         Good
7       26.203704         Good
8       27.037037         Good
9       42.361111         Good

In [40]:
df

,date,pm10,pm2_5,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,aerosol_optical_depth,dust,uv_index,...,co_aqi,no2_ppb,no2_aqi,so2_ppb,so2_aqi,o3_ppb,o3_aqi,calculated_aqi,co_ppm,aqi_category
0,2022-08-01,27.152632,18.984211,328.157895,13.226316,5.373684,75.526316,NaN,NaN,NaN,...,3.255112,7.029234,6.631353,2.050800,2.929715,38.472660,35.622833,69.415449,0.286450,Moderate
1,2022-08-02,27.152632,18.984211,328.157895,13.226316,5.373684,75.526316,NaN,NaN,NaN,...,3.255112,7.029234,6.631353,2.050800,2.929715,38.472660,35.622833,69.415449,0.286450,Moderate
2,2022-08-03,27.152632,18.984211,328.157895,13.226316,5.373684,75.526316,NaN,NaN,NaN,...,3.255112,7.029234,6.631353,2.050800,2.929715,38.472660,35.622833,69.415449,0.286450,Moderate
3,2022-08-04,27.152632,18.984211,328.157895,13.226316,5.373684,75.526316,0.491053,0.421053,2.094737,...,3.255112,7.029234,6.631353,2.050800,2.929715,38.472660,35.622833,69.415449,0.286450,Moderate
4,2022-08-05,15.529167,10.879167,237.875000,13.645833,6.395833,52.833333,0.221667,0.000000,1.066667,...,2.359565,7.252190,6.841689,2.440891,3.486987,26.912988,24.919434,54.314797,0.207642,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1293,2026-02-14,50.154167,48.300000,673.416667,10.266667,14.766667,127.916667,0.460833,2.875000,1.810417,...,6.679854,5.456304,5.147457,5.635516,8.050738,65.159996,84.189319,132.517588,0.587827,Poor
1294,2026-02-15,62.729167,60.625000,845.750000,15.004167,15.500000,126.958333,0.678333,3.625000,1.735417,...,8.389288,7.974087,7.522724,5.915384,8.450549,64.671826,82.594632,154.592632,0.738257,Severe
1295,2026-02-16,70.454167,68.583333,687.208333,13.158333,15.329167,130.000000,0.698750,3.208333,1.702083,...,6.816658,6.993104,6.597268,5.850188,8.357411,66.221233,87.656029,160.171435,0.599866,Severe
1296,2026-02-17,51.379167,50.233333,552.916667,7.229167,12.458333,127.333333,0.540833,1.916667,1.879167,...,5.484572,3.842000,3.624528,4.754570,6.792242,64.862849,83.218640,137.278057,0.482642,Poor
1297,2026-02-18,43.029167,41.875000,540.666667,6.883333,11.441667,123.666667,0.430417,1.625000,1.975000,...,5.363060,3.658204,3.451136,4.366571,6.237959,62.995071,77.117231,116.697236,0.471949,Poor