In [15]:
import pandas as pd

df = pd.read_csv("Sleep_health_and_lifestyle_dataset.csv")

In [16]:
df.shape

(374, 13)

In [17]:
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [18]:
factors = [
    'Sleep Duration',
    'Quality of Sleep',
    'Stress Level',
    'Physical Activity Level',
    'Heart Rate'
]
df[factors].head()

,Sleep Duration,Quality of Sleep,Stress Level,Physical Activity Level,Heart Rate
0,6.1,6,6,42,77
1,6.2,6,8,60,75
2,6.2,6,8,60,75
3,5.9,4,8,30,85
4,5.9,4,8,30,85

In [19]:
df['duration_score'] = (df['Sleep Duration'] / 8 * 100).clip(upper=100)
df[['Sleep Duration', 'duration_score']].head()

   Sleep Duration  duration_score
0             6.1           76.25
1             6.2           77.50
2             6.2           77.50
3             5.9           73.75
4             5.9           73.75

In [20]:
df['quality_score'] = df['Quality of Sleep'] / 10 * 100
df[['Quality of Sleep', 'quality_score']].head()

   Quality of Sleep  quality_score
0                 6           60.0
1                 6           60.0
2                 6           60.0
3                 4           40.0
4                 4           40.0

In [21]:
df['stress_score'] = (10 - df['Stress Level']) / 9 * 100
df[['Stress Level', 'stress_score']].head()

   Stress Level  stress_score
0             6     44.444444
1             8     22.222222
2             8     22.222222
3             8     22.222222
4             8     22.222222

In [22]:
df['activity_score'] = (df['Physical Activity Level'] / 60 * 100).clip(upper=100)
df[['Physical Activity Level', 'activity_score']].head()

   Physical Activity Level  activity_score
0                       42            70.0
1                       60           100.0
2                       60           100.0
3                       30            50.0
4                       30            50.0

In [23]:
df['heart_rate_score'] = (
    (100 - df['Heart Rate']) / 40 * 100
).clip(lower=0, upper=100)
df[['Heart Rate', 'heart_rate_score']].head()

   Heart Rate  heart_rate_score
0          77              57.5
1          75              62.5
2          75              62.5
3          85              37.5
4          85              37.5

In [24]:
df['sleep_score'] = (
    0.30 * df['duration_score'] +
    0.30 * df['quality_score'] +
    0.15 * df['stress_score'] +
    0.15 * df['activity_score'] +
    0.10 * df['heart_rate_score']
)
df[['Sleep Duration',
    'Quality of Sleep',
    'Stress Level',
    'Physical Activity Level',
    'Heart Rate',
    'sleep_score']].head()

,Sleep Duration,Quality of Sleep,Stress Level,Physical Activity Level,Heart Rate,sleep_score
0,6.1,6,6,42,77,63.791667
1,6.2,6,8,60,75,65.833333
2,6.2,6,8,60,75,65.833333
3,5.9,4,8,30,85,48.708333
4,5.9,4,8,30,85,48.708333

In [25]:
def classify_sleep(score):
    if score >= 80:
        return "Good"
    elif score >= 60:
        return "Average"
    else:
        return "Poor"
    
df['sleep_category'] = df['sleep_score'].apply(classify_sleep)
df[['sleep_score', 'sleep_category']].head(10)

   sleep_score sleep_category
0    63.791667        Average
1    65.833333        Average
2    65.833333        Average
3    48.708333           Poor
4    48.708333           Poor
5    48.708333           Poor
6    61.125000        Average
7    79.416667        Average
8    79.416667        Average
9    79.416667        Average

In [26]:
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,duration_score,quality_score,stress_score,activity_score,heart_rate_score,sleep_score,sleep_category
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN,76.25,60.0,44.444444,70.0,57.5,63.791667,Average
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN,77.50,60.0,22.222222,100.0,62.5,65.833333,Average
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN,77.50,60.0,22.222222,100.0,62.5,65.833333,Average
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,73.75,40.0,22.222222,50.0,37.5,48.708333,Poor
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,73.75,40.0,22.222222,50.0,37.5,48.708333,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,100.00,90.0,77.777778,100.0,80.0,91.666667,Good
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,100.00,90.0,77.777778,100.0,80.0,91.666667,Good
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,100.00,90.0,77.777778,100.0,80.0,91.666667,Good
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,100.00,90.0,77.777778,100.0,80.0,91.666667,Good
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,100.00,90.0,77.777778,100.0,80.0,91.666667,Good